export type Severity = "bloquant" | "critique" | "important" | "amelioration";

export interface FindingSeed {
  code: string;
  severity: Severity;
  category: string;
  title: string;
  problem: string;
  why: string;
  fix: string;
  files: string;
  autoFixed: boolean;
}

export const FINDINGS: FindingSeed[] = [
  {
    code: "AUTH-01",
    severity: "bloquant",
    category: "Authentification",
    title: "Le lien d'invitation aboutit toujours à « lien invalide »",
    problem:
      "inviteUserByEmail() est appelé côté serveur avec la clé service_role : Supabase utilise alors le flux « implicite » et place la session dans le fragment de l'URL (#access_token=…). La redirection pointe vers la route serveur /auth/confirm, qui ne voit jamais ce fragment : ni token_hash ni code → redirection vers /login?error=lien_invalide. Et même en arrivant sur /auth/set-password, le client @supabase/ssr (en mode PKCE) ne traite pas ces jetons automatiquement.",
    why:
      "C'est très probablement l'étape qui te bloque : aucun utilisateur invité ne peut activer son compte, donc aucun employé, manager ou RH ne peut se connecter.",
    fix:
      "La page /auth/set-password gère maintenant explicitement les 3 formats (#access_token → setSession, ?token_hash → verifyOtp, ?code → exchangeCodeForSession) et affiche l'erreur exacte (lien expiré…). L'invitation redirige directement vers cette page. /auth/confirm laisse passer le fragment au lieu de renvoyer vers « lien invalide » (les invitations déjà envoyées fonctionnent donc aussi).",
    files: "app/auth/set-password/page.tsx, app/auth/confirm/route.ts, lib/actions/users.ts",
    autoFixed: true,
  },
  {
    code: "AUTH-02",
    severity: "critique",
    category: "Authentification",
    title: "NEXT_PUBLIC_SITE_URL absente → lien vers « undefined/auth/… » ou localhost",
    problem:
      "redirectTo est construit avec process.env.NEXT_PUBLIC_SITE_URL sans valeur de secours. Si la variable manque sur Vercel (ou si le redéploiement n'a pas été fait), Supabase rejette l'URL et retombe sur la Site URL (souvent localhost:3000).",
    why: "L'invité reçoit un lien qui ne mène nulle part : même symptôme que AUTH-01, et difficile à diagnostiquer.",
    fix: "Fonction getSiteUrl() : utilise la variable si elle existe, sinon déduit l'URL de la requête (x-forwarded-host). Vérifier aussi « Redirect URLs » dans Supabase : https://ton-app.vercel.app/**",
    files: "lib/actions/users.ts",
    autoFixed: true,
  },
  {
    code: "AUTH-03",
    severity: "important",
    category: "Authentification",
    title: "Profil créé à la main pour le premier admin (instructions contradictoires)",
    problem:
      "Le README demande à la fois de « mettre ton rôle à admin » dans profiles (étape 1.4) et d'« ajouter une ligne » (étape 4). Aucune ligne profiles n'est créée automatiquement : un compte sans profil voit une application vide avec le rôle par défaut.",
    why: "Source d'erreurs à l'installation et de comptes « fantômes ».",
    fix: "Migration 0005 : trigger on_auth_user_created qui crée le profil (rôle employe) à chaque nouveau compte + rattrapage des comptes existants. inviteUser fait un upsert au lieu d'un insert. Le premier admin : une seule requête « update profiles set role='admin' where email=… ».",
    files: "supabase/migrations/0005_corrections.sql, lib/actions/users.ts",
    autoFixed: true,
  },
  {
    code: "AUTH-04",
    severity: "important",
    category: "Authentification",
    title: "Un admin peut supprimer son compte ou se retirer ses droits",
    problem: "updateUserRole et deleteUserAccount n'empêchent pas l'admin d'agir sur lui-même ; le rôle reçu n'est pas validé.",
    why: "Risque de verrouillage total de l'application (plus aucun admin).",
    fix: "Garde-fous ajoutés + validation de la liste des rôles autorisés.",
    files: "lib/actions/users.ts",
    autoFixed: true,
  },
  {
    code: "UPL-01",
    severity: "critique",
    category: "Documents & fichiers",
    title: "Upload de documents > 1 Mo impossible",
    problem:
      "Les documents passent par une Server Action. Next.js limite leur corps à 1 Mo par défaut → « Body exceeded 1 MB limit » pour un contrat scanné ou un diplôme PDF.",
    why: "La plupart des pièces RH scannées dépassent 1 Mo : l'onglet Documents est quasi inutilisable.",
    fix: "experimental.serverActions.bodySizeLimit = '10mb' dans next.config.mjs + contrôle de taille explicite avec message clair. (Attention : Vercel limite à 4,5 Mo par requête ; pour plus gros, passer à un upload direct navigateur → Storage via URL signée.)",
    files: "next.config.mjs, lib/actions/documents.ts",
    autoFixed: true,
  },
  {
    code: "UPL-02",
    severity: "critique",
    category: "Documents & fichiers",
    title: "Noms de fichiers avec accents refusés (« Invalid key »)",
    problem: "Le chemin Storage est construit avec file.name brut. Supabase Storage refuse les clés avec accents/caractères spéciaux : « Diplôme d'ingénieur.pdf » échoue.",
    why: "En contexte francophone, c'est la majorité des fichiers.",
    fix: "Nouvelle fonction safeStorageName() (retire accents et caractères spéciaux) utilisée pour les documents et les photos. Le nom d'origine reste affiché (colonne file_name). Suppression du fichier si l'insertion en base échoue.",
    files: "lib/storage-path.ts, lib/actions/documents.ts, components/photo-uploader.tsx",
    autoFixed: true,
  },
  {
    code: "UPL-03",
    severity: "important",
    category: "Documents & fichiers",
    title: "L'employé voit ses documents listés mais sans lien de téléchargement",
    problem: "La table employee_documents autorise la lecture par l'employé, mais la policy Storage du bucket employee-documents est réservée admin/rh → createSignedUrl échoue.",
    why: "Incohérence entre la base et le stockage.",
    fix: "Policy storage_documents_self_read : l'employé lit les fichiers de son propre dossier ({employee_id}/…).",
    files: "supabase/migrations/0005_corrections.sql",
    autoFixed: true,
  },
  {
    code: "PAY-01",
    severity: "critique",
    category: "Paie",
    title: "Montants mal affichés dans le PDF du bulletin",
    problem: "toLocaleString('fr-FR') insère une espace fine insécable (U+202F) comme séparateur de milliers. La police Helvetica intégrée à @react-pdf n'a pas ce glyphe → « 250/000 F » ou caractère manquant.",
    why: "Un bulletin de paie avec des montants illisibles n'est pas présentable.",
    fix: "Remplacement de U+202F / U+00A0 par une espace classique, et unité « FCFA ».",
    files: "lib/payslip-pdf.tsx",
    autoFixed: true,
  },
  {
    code: "PAY-02",
    severity: "critique",
    category: "Paie",
    title: "Une période « validée » reste modifiable, et les brouillons sont visibles par l'employé",
    problem: "savePayslip/generatePayslipPdf ne vérifient pas le statut de la période. « Mes bulletins » affiche tout bulletin dont le PDF existe, même en brouillon.",
    why: "Un bulletin remis au salarié ne doit plus changer ; un brouillon en cours de correction ne doit pas lui être montré.",
    fix: "Refus côté serveur si la période est validée + trigger SQL trg_payslips_lock (protection en base) + policy payslips_self_read limitée aux périodes validées (via fonctions security definer pour éviter une récursion RLS).",
    files: "lib/actions/payroll.tsx, app/(app)/my-payslips/page.tsx, supabase/migrations/0005_corrections.sql",
    autoFixed: true,
  },
  {
    code: "SEC-01",
    severity: "important",
    category: "Sécurité",
    title: "Menus Paie/Administration visibles et accessibles pour tous les rôles",
    problem: "La TopNav affiche tous les liens ; aucune garde serveur sur /admin et /payroll. La RLS protège les données, mais un employé voit des écrans vides et des formulaires qui échouent.",
    why: "Mauvaise expérience et surface d'attaque inutile.",
    fix: "lib/auth.ts → requireRole() utilisé dans des layouts admin/ et payroll/ ; /admin/users réservé admin ; menu filtré par rôle. La barre de recherche décorative lance maintenant une vraie recherche.",
    files: "lib/auth.ts, app/(app)/admin/layout.tsx, app/(app)/payroll/layout.tsx, components/top-nav.tsx",
    autoFixed: true,
  },
  {
    code: "SEC-02",
    severity: "important",
    category: "Sécurité",
    title: "Mises à jour refusées par la RLS affichées comme réussies",
    problem: "Avec Supabase, un UPDATE bloqué par la RLS ne renvoie pas d'erreur : il modifie 0 ligne. updateEmployee retournait donc un succès.",
    why: "L'utilisateur croit avoir enregistré alors que rien n'a changé.",
    fix: "Ajout de .select('id') et contrôle du nombre de lignes modifiées. À généraliser aux autres actions (delete*, updateUserRole…).",
    files: "lib/actions/employees.ts",
    autoFixed: true,
  },
  {
    code: "SEC-03",
    severity: "important",
    category: "Sécurité",
    title: "Recherche employés : injection dans le filtre PostgREST",
    problem: "Le texte recherché est injecté tel quel dans .or(). Une virgule ou une parenthèse casse la requête (liste vide) ou modifie le filtre.",
    why: "Bug visible (« Koné, Aïcha » ne renvoie rien) et risque de manipulation du filtre.",
    fix: "Nettoyage des caractères réservés , ( ) * % : \\ avant construction du filtre.",
    files: "app/(app)/employees/page.tsx",
    autoFixed: true,
  },
  {
    code: "SEC-04",
    severity: "important",
    category: "Sécurité",
    title: "Fonction security definer sans search_path + absence de .gitignore",
    problem: "current_role_is est security definer sans « set search_path » (alerte du linter Supabase). Le dépôt n'a ni .gitignore ni .env.example (pourtant cité dans le README) : risque de commiter .env.local avec la clé service_role.",
    why: "Une clé service_role publiée sur GitHub = accès total à toutes les données RH.",
    fix: "search_path fixé dans la migration 0005 ; ajout de .gitignore et .env.example. Si un .env a déjà été poussé un jour : régénérer les clés dans Supabase.",
    files: ".gitignore, .env.example, supabase/migrations/0005_corrections.sql",
    autoFixed: true,
  },
  {
    code: "DATA-01",
    severity: "important",
    category: "Données RH (Côte d'Ivoire)",
    title: "Champs RH indispensables manquants sur la fiche employé",
    problem: "Pas de matricule, N° CNPS, N° CNI/passeport, catégorie professionnelle (convention collective interprofessionnelle), nombre d'enfants/parts (ITS), RIB/mode de paiement.",
    why: "Ces informations sont nécessaires pour un bulletin de paie conforme et les déclarations CNPS/DGI.",
    fix: "À ajouter dans une migration 0006 + formulaire employé (recommandation, non incluse dans le patch pour ne pas modifier ton modèle de données sans ton accord).",
    files: "supabase/migrations, components/employee-form.tsx",
    autoFixed: false,
  },
  {
    code: "DATA-02",
    severity: "important",
    category: "Paie",
    title: "Bulletin PDF incomplet (mentions obligatoires)",
    problem: "Le nom de l'entreprise est codé en dur (« Mon Entreprise »). Manquent : adresse, N° CNPS employeur, N° compte contribuable, matricule et N° CNPS du salarié, catégorie, ancienneté, distinction brut / cotisations / net.",
    why: "Un bulletin de paie doit comporter ces mentions pour avoir une valeur légale.",
    fix: "Créer une table « company_settings » éditable dans Administration et enrichir PayslipPdf (recommandation).",
    files: "lib/actions/payroll.tsx, lib/payslip-pdf.tsx",
    autoFixed: false,
  },
  {
    code: "DATA-03",
    severity: "amelioration",
    category: "Données RH (Côte d'Ivoire)",
    title: "Photos des employés dans un bucket public",
    problem: "Le bucket employee-photos est public : toute personne ayant l'URL voit la photo, sans être connectée.",
    why: "Donnée personnelle (loi n°2013-450 relative aux données à caractère personnel, ARTCI).",
    fix: "Passer le bucket en privé et servir les photos via URL signée (recommandation).",
    files: "supabase/migrations/0002_extend_employees.sql, components/photo-uploader.tsx",
    autoFixed: false,
  },
  {
    code: "QUAL-01",
    severity: "amelioration",
    category: "Qualité du code",
    title: "Typage Supabase désactivé (Database = any)",
    problem: "Tout le typage des requêtes est perdu : les fautes de nom de colonne ne sont détectées qu'à l'exécution. Nombreux « as any ».",
    why: "Plus le projet grandit, plus les régressions silencieuses se multiplient.",
    fix: "npx supabase gen types typescript --project-id <id> > lib/database.types.ts puis createClient<Database>().",
    files: "lib/types.ts",
    autoFixed: false,
  },
  {
    code: "QUAL-02",
    severity: "amelioration",
    category: "Qualité du code",
    title: "Erreurs ignorées dans les actions secondaires",
    problem: "createEmployee n'examine pas les erreurs de l'historique/contrat/rémunération ; les delete* et validatePayRun ne remontent aucune erreur ; pas d'audit log (qui a modifié quoi).",
    why: "Données partielles possibles et impossibilité de tracer les modifications sensibles (salaires).",
    fix: "Vérifier chaque { error }, idéalement regrouper la création dans une fonction SQL (transaction), ajouter une table audit_log alimentée par trigger (recommandation).",
    files: "lib/actions/*.ts",
    autoFixed: false,
  },
  {
    code: "QUAL-03",
    severity: "amelioration",
    category: "Fonctionnel",
    title: "Pas de « mot de passe oublié » ni de « renvoyer l'invitation »",
    problem: "Si un lien d'invitation expire (24 h par défaut) ou est « consommé » par l'antivirus de messagerie (Outlook Safe Links), l'admin doit supprimer puis recréer le compte.",
    why: "Cas très fréquent en entreprise.",
    fix: "Ajouter un bouton « Renvoyer » (auth.admin.generateLink type recovery) et une page « Mot de passe oublié » (resetPasswordForEmail → /auth/set-password, déjà compatible).",
    files: "components/admin/users-admin.tsx, app/login/page.tsx",
    autoFixed: false,
  },
];

export const STRENGTHS = [
  "Stack moderne et cohérente : Next.js App Router + Server Actions + Supabase + Tailwind, hébergement Vercel.",
  "Row Level Security activée sur toutes les tables, avec des rôles clairs (admin, rh, manager, employé).",
  "Clé service_role utilisée uniquement côté serveur, après vérification du rôle admin.",
  "Migrations SQL versionnées, commentées et lisibles ; référentiels (départements, services, postes, sites) bien normalisés.",
  "Bonne couverture fonctionnelle : dossier du personnel, contrats, rémunération, documents, organigramme calculé, paie avec PDF archivé.",
  "Bons réflexes UX : ancienneté calculée à la volée, URL signées pour les fichiers privés, saisie des montants négatifs bien pensée.",
  "Code et README très bien commentés en français : facile à reprendre.",
];
